[package]
name = "ttd-v2"
version = "0.2.2"
edition = "2021"

[dependencies]
chrono = { version="0.4.38", features=["serde"] }
crossterm = "0.28.1"
ratatui = "0.29.0"
serde = { version="1.0.215", features=["derive"] }
serde_json = "1.0.133"
tui-input = "0.11.0"
